name: myenv
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.01.10=haa95532_0
  - certifi=2022.12.7=py311haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - libffi=3.4.2=hd77b12b_6
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py311h2bbff1b_0
  - mkl_fft=1.3.1=py311h743a336_0
  - mkl_random=1.2.2=py311heda8569_0
  - numpy=1.23.5=py311h54701ec_0
  - numpy-base=1.23.5=py311h0424125_0
  - openssl=1.1.1t=h2bbff1b_0
  - pip=23.0.1=py311haa95532_0
  - python=3.11.2=h966fe2a_0
  - setuptools=65.6.3=py311haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.1=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2022g=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py311haa95532_0
  - wincertstore=0.2=py311haa95532_0
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.0
    - bleach==6.0.0
    - cffi==1.15.1
    - colorama==0.4.6
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distro==1.8.0
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fonttools==4.39.3
    - fqdn==1.5.1
    - idna==3.4
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.1.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - nbclassic==0.5.4
    - nbclient==0.7.2
    - nbconvert==7.2.10
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.4
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.14.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pywin32==306
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzmq==25.0.2
    - qtconsole==5.4.1
    - qtpy==2.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tabula-py==2.7.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.9.0
    - uri-template==1.2.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.7
